<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Rotbarsch.Reqnroll.VsTestConsoleLogger.TestLogger</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cucumber.Messages" Version="30.1.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.*" />
    <PackageReference Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>

</Project>
